# Generated by Django 6.0.2 on 2026-04-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('JALAN', 'Jalan Rusak'), ('LAMPU', 'Lampu Jalan'), ('AIR', 'Pipa Air'), ('SAMPAH', 'Penumpukan Sampah'), ('LAINNYA', 'Lainnya')], default='LAINNYA', max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('REPORTED', 'Dilaporkan'), ('IN_PROGRESS', 'Sedang Diproses'), ('RESOLVED', 'Selesai'), ('REJECTED', 'Ditolak')], default='REPORTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
