# Generated by Django 6.0.2 on 2026-04-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('JALAN', 'Jalan Rusak'), ('LAMPU', 'Lampu Jalan'), ('AIR', 'Pipa Air'), ('SAMPAH', 'Penumpukan Sampah'), ('LAINNYA', 'Lainnya'), ('ALL', 'Semua Kategori')], default='LAINNYA', max_length=20),
        ),
    ]
