# Generated by Django 4.2.7 on 2026-07-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_report_reporter_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('JALAN', 'Jalan Rusak'), ('LAMPU', 'Lampu Jalan'), ('AIR', 'Pipa Air'), ('SAMPAH', 'Penumpukan Sampah'), ('LAINNYA', 'Lainnya'), ('ALL', 'Semua Kategori'), ('Infrastruktur', 'Infrastruktur'), ('Fasilitas Umum', 'Fasilitas Umum'), ('Kebersihan', 'Kebersihan'), ('Keamanan', 'Keamanan'), ('Lainnya', 'Lainnya')], default='LAINNYA', max_length=20),
        ),
    ]
